# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GfUz2-HG9b9RbJlGtJFEu3oZU8OHWykU
"""

import pandas as pd
data=pd.read_excel('/content/classdata.xlsx','Sheet1')
data

import pandas as pd
data=[
    ('kishore','22bam045','aiml')
]
df=pd.DataFrame(data, columns = ['Name','Regno','Class'])
df

import pandas as pd
data=[
  {'Name':'Kishore','Regno':'22Bam045','Class':'Aiml'}
]
data=pd.DataFrame(data)
data

import pandas as pd
data=pd.read_csv('/content/weather.csv',skiprows=1,names=['date','temp','windspeed','event'],nrows=5,na_values=('not','Na'))
#data[['date','event']][data.temp==data['temp'].max()]
data

